### PR TITLE
Update ahk.py

### PR DESCRIPTION
**Pull request by itayVolk**
Added a tag list to the message sent after tagging, allowing people to see a post's tags without leaving it on desktop.

### CODE REVIEW

**Comment by Run1e** [comment]
I don't think a lot of people are posting AHK help on phones, and if they are, and are unsure what they just tagged, they can probably just swipe out of the channel for a second imo?

**Comment by itayVolk** [comment]
You can see the tags on mobile, but you can't see them on PC.
While swiping out briefly is possible on PC there have been threads where helpers didn't notice the tags (especially the version tags).

**Comment by itayVolk** [comment]
For example:
pc:
pc
mobile (android):
mobile (android)

**Comment by Run1e** [comment]
I see

I think it would look nicer and much less cramped formatted something like

```
Thanks for tagging your post!

- tag 1
- tag 2
- tag 3

**If your issue gets solved, you can mark your post as solved by sending `/solved`**

**Comment by itayVolk** [comment]
Okay, I'll change the format after I finish the /solved branch.

**Comment by Run1e** [comment]
merged

**Pull request closed without merging**
